### PR TITLE
add setup script for linux

### PR DESCRIPTION
**Pull request by gaochua**
Add infection monkey setup script for **Linux** based on [setup guide](https://github.com/guardicore/monkey/blob/master/monkey/infection_monkey/readme.txt)

### CODE REVIEW

**Comment by VakarisZ** [comment]
This just looks like a portion of deployment scripts code with hardcoded urls. What is a purpose of this script? For dependencies there are deployment scripts. For building monkey there is `build_linux` script. If you want a script that only install dependencies for monkey and not for island, it would be better to improve deployment scripts with arguments '--monkey-only' and '--island-only'

**Comment by gaochua** [comment]
Yes, I haven't looked at `deployment_scripts`. The purpose of this script is to automate installation steps described in `monkey/readme.txt`.

**Comment by VakarisZ** [comment]
Deployment scripts automate both, steps in `monkey_island/readme.txt` and in `infection_monkey/readme.txt`. It's good that you want to contribute, but I don't want to approve this PR, because it's one more script we will have to support each time build process changes.

**Comment by gaochua** [comment]
Yes, I'll close this PR

**Comment by VakarisZ** [comment]
@gaochua Feel free to improve/try deployment scripts. Installing only monkey/island dependencies is a welcome improvement! Then we could have your script in this directory. Your script could call deployment script and pass --monkey-only parameter and achieve the same!

**Pull request closed without merging**
