### PR TITLE
3418 install all safe

### PR DESCRIPTION
**Pull request by cakekoa**
# What does this PR do?

Fixes part of #3418.

Implements the "Install All Safe" button.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

### CODE REVIEW

**Comment by shreyamalviya** [comment]
What if we position it like this?


Similar to the Installed Plugins tab:

Unrelated to this PR but I also feel the spacing should be fixed between these ones.

**Review by shreyamalviya — CHANGES_REQUESTED** [review]
Found a bug with the buttons:

https://github.com/guardicore/monkey/assets/44770317/2db28bfd-420f-4f1f-be3c-d73c5b763ec2

After I click on "Install All Safe", it just installs the plugins for a while. Go to 0:25 to see the bug.

**Review by shreyamalviya — CHANGES_REQUESTED** [review]
The button should be disabled if no safe plugins are available.

**Comment by VakarisZ** [comment]
Agree with Shreya: 
1. button should be up top somewhere. Another option: 
image
2. button should be disabled once no safe options are left

**Pull request merged**
