### PR TITLE
Shellshock timeout exception handling

### PR DESCRIPTION
**Pull request by VakarisZ**
# Feature / Fixes
> Sending requests in shellshock module had no timeout handling.
shellshockbug

If timeout happens for any request, we just continue sending other requests. At the end we inform that timeout happened (we don't inform about particular urls because that would trash the log)

### CODE REVIEW

**Comment by danielguardicore** [comment]
I want to make sure I understand.
This PR handles the case where the monkey runs into a timeout while it's sending the _n_ HEAD requests, to save sending the rest of the requests?

**Comment by VakarisZ** [comment]
No (but I can easily change it to break the loop if a timeout occurs). This PR only handles the error in a proper fashion. Monkey still tries to send all of the requests. If one or more requests get timeout error it is silently handled and at the end of request sending the user is informed with something like: "One or more requests timed out"

**Comment by danielguardicore** [comment]
Without the break, I don't understand what this improves on current code

**Comment by VakarisZ** [comment]
It handles timeout error (error shown in screenshot above)

**Comment by VakarisZ** [comment]
Added break. Now it breaks if timeout happens

**Pull request merged**
