### PR TITLE
Bugfix, installer should go according to Python bitnes

### PR DESCRIPTION
**Pull request by danielguardicore**
This handles cases where we run 32b python on 64b machines

## Checklist
* [X] Have you added an explanation of what your changes do and why you'd like to include them?
* [X] Have you successfully tested your changes locally?
* [ ] Is the TravisCI build passing?

### CODE REVIEW

**Comment by danielguardicore** [comment]
@VakarisZ can you check this on your Windows build machines?

**Comment by VakarisZ** [comment]
It wasn't working before? I can build, but I don't have any modern 32 bit win to test binaries.

**Comment by VakarisZ** [comment]
Built and tested on win 10 64 bit. Runs fine, downloads 64 bit monkey as it should.

**Comment by danielguardicore** [comment]
> It wasn't working before? I can build, but I don't have any modern 32 bit win to test binaries.

This only affected Linux builds, and it meant the spec file looked at the kernel version and not python version. 
So if I built the Monkey on a 64b machine with 32b python, it'd include traceroute64 and not traceroute32

**Pull request merged**
