### PR TITLE
Password hash

### PR DESCRIPTION
**Pull request by PrajwalM2212**
# What does this PR do? 
Hashes the password on server side instead of client side

Fixes #`put issue number here`. 
https://github.com/guardicore/monkey/issues/969

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
I have tested these changes yet. I have read the relevant code and made appropriate changes.
@mssalvatore Should we use https://flask-bcrypt.readthedocs.io/en/latest/ for salting ?

**Comment by mssalvatore** [comment]
I'm good with using bcrypt instead of sha3_512.

**Comment by acepace** [comment]
> sha3_512

This requires updating the relevant docs to explain how to debug this?

**Comment by shreyamalviya** [comment]
Continued in #1139

**Pull request closed without merging**
