### PR TITLE
Update package.json: Adding tsparticles dependency

### PR DESCRIPTION
**Pull request by CruxBox**
# What does this PR do? 

To run the monkey_island node server, tsparticles dependency is required.
This is currently missing in package.json, causing compilation to fail.
Hence, updating package.json to account for the dependency.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing? 
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...} 
* [ ] If applicable, add screenshots or log transcripts of the feature working

## Explain Changes

Are the commit messages enough? If not, elaborate.

### CODE REVIEW

**Comment by CruxBox** [comment]
I am not entirely sure if this is the right fix.
I tried building moneky_island server using this [guide](https://github.com/guardicore/monkey/tree/develop/monkey/monkey_island) and couldn't get it running on Linux without manually installing tsparticles.
Maybe someone better aquainted with npm can fix whatever the issue is.

**Comment by VakarisZ** [comment]
Try the deployment scripts. Which linux? We don't even use node server IIRC

**Comment by CruxBox** [comment]
Ah, well I might be wrong about it being a node server. Basically tried setting the monkey_island server after following the instructions from the guide on PopOS.

I'll try the deployment scripts and let you know

**Comment by VakarisZ** [comment]
Join our [slack](https://join.slack.com/t/infectionmonkey/shared_invite/enQtNDU5MjAxMjg1MjU1LWM0NjVmNWE2ZTMzYzAxOWJiYmMxMzU0NWU3NmUxYjcyNjk0YWY2MDkwODk4NGMyNDU4NzA4MDljOWNmZWViNDU) and we'll help you with the setup

**Pull request closed without merging**
