### PR TITLE
Project: Add pre-commit hook for prettier

### PR DESCRIPTION
**Pull request by cakekoa**
# What does this PR do?

Fixes part of #3070.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?
* [ ] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [ ] If applicable, add screenshots or log transcripts of the feature working

### CODE REVIEW

**Review by mssalvatore — COMMENTED** [review]
Do we have a config file for prettier and does this hook use it?

**Comment by cakekoa** [comment]
> Do we have a config file for prettier and does this hook use it?

We have one in the next_ui directory, and it will use it for files under that directory. Should I just have the pre-commit hook target that directory?

**Comment by mssalvatore** [comment]
> > Do we have a config file for prettier and does this hook use it?
> 
> We have one in the next_ui directory, and it will use it for files under that directory. Should I just have the pre-commit hook target that directory?

Either that or move the config to the top level.

**Comment by cakekoa** [comment]
Closing, as this is already configured to be run as part of eslint

**Pull request closed without merging**
