### PR TITLE
Fix data dir plugin overwrite

### PR DESCRIPTION
**Pull request by mssalvatore**
# What does this PR do?

Prevents plugins in the `data_dir` from being overwritten on Island startup

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Do all unit tests pass?
* [ ] Do all end-to-end tests pass?

### CODE REVIEW

**Comment by mssalvatore** [comment]
@shreyamalviya Can you help me figure out why the Windows test is failing? `assert_windows_permissions()` succeeds if I call it on the data directory (created with create_secure_directory()) but not if I call it on the plugin directory (also created with create_secure_directory(). It seems that it succeeds on a secured directory, but not on the child of a secured directory.

**Comment by shreyamalviya** [comment]
This happens because `acl.GetExplicitEntriesFromAcl()` seems to only retrieve ACEs which don't have the `INHERITED_ACE` flag set. When we're creating a secure directory in WIndows, we're setting the `CONTAINER_INHERIT_ACE` and `OBJECT_INHERIT_ACE` so that any children inherit the same permissions, and the `INHERITED_ACE` flag is hence set on them.


I'm working on a clean fix.

**Comment by shreyamalviya** [comment]
Modified windows' secure directory creation to set the `SE_DACL_PROTECTED` flag so that  if a new secure directory is being created inside a directory with ACE inheritance set, it won't inherit the parent ACE and will use the one given to it.

image

**Review by cakekoa — APPROVED** [review]
Nice work -- I especially like these unit tests

**Pull request merged**
